language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: lint, test and build
      name: lint
      script: npm run lint
    - name: test
      script:
        - npm test -- --ci --coverage
        - npm run coveralls
    - name: build
      script: make build
    - stage: commitlint
      script: npm run commitlint
      if: sender NOT IN ('dependabot[bot]', 'dependabot-preview[bot]')
    - stage: deploy
      script: make build && npm run release
      if: branch = master
